# Generated by Django 3.0.8 on 2020-08-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
