# Generated by Django 3.0.8 on 2020-08-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_auto_20200801_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_period', to='userapi.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tz',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
