# Generated by Django 3.0.8 on 2020-08-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_auto_20200801_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tz',
            field=models.CharField(max_length=50),
        ),
    ]
